### ISSUE TITLE
Pictures

### ISSUE THREAD

**Issue by bitdust** [bitdust/EarthLiveSharp#1]
![clipboard05](https://cloud.githubusercontent.com/assets/6072743/11613119/73ea46c8-9c50-11e5-92e7-cfcba2558c1f.png)
![clipboard07](https://cloud.githubusercontent.com/assets/6072743/11613120/7a4230c6-9c50-11e5-91b4-08bea023dfe8.png)
![1](https://cloud.githubusercontent.com/assets/6072743/11613124/a73b086e-9c50-11e5-9253-9510ed0528e8.png)

**Comment by bitdust** [comment]
![image](https://cloud.githubusercontent.com/assets/6072743/11845286/2bf0cc9c-a44e-11e5-89b7-5600791606ae.png)

**Comment by Iamanorange** [comment]
广告做得好啊！

**Comment by bitdust** [comment]
@Iamanorange 
别提了，我的CDN账户已经炸了怎么说。。有人赔吗（抠鼻~）

**Comment by bitdust** [comment]
![qq 20160808164555](https://cloud.githubusercontent.com/assets/6072743/17474278/b7e1bf20-5d87-11e6-82c9-fc1b528b042d.png)

**Comment by bitdust** [comment]
![capture_003_11032017_160323](https://cloud.githubusercontent.com/assets/6072743/23821657/7d53554e-0674-11e7-8ccc-260070261967.png)

**Comment by bitdust** [comment]
![unnamed qq screenshot20170410213159](https://cloud.githubusercontent.com/assets/6072743/24863990/74d1df7a-1e35-11e7-9f06-de77ea366871.png)
![unnamed qq screenshot20170410213253](https://cloud.githubusercontent.com/assets/6072743/24863992/76d09f64-1e35-11e7-9e48-55e882d56d4a.png)

**Comment by bitdust** [comment]
![28](https://cloud.githubusercontent.com/assets/6072743/25012185/50a6e842-20a2-11e7-8ff3-e232bf3ba7c4.png)

**Comment by bitdust** [comment]
![1166632212](https://user-images.githubusercontent.com/6072743/35085914-8b1af33e-fc65-11e7-9f46-3f04517e5833.png)

**Comment by bitdust** [comment]
![_20180713215137](https://user-images.githubusercontent.com/6072743/42695112-f4cde686-86e6-11e8-97e3-799db330fa67.png)
