### ISSUE TITLE
可以切换卫星以显示不同地区的实时图片吗

### ISSUE THREAD

**Issue by zx563147474** [bitdust/EarthLiveSharp#11]
比如国内的设为某一特定卫星拍摄的图片，美国或者其他地区的设为对应的当地卫星拍摄的图片

**Comment by Iamanorange** [comment]
>全世界已发射的搭载可见光相机的地球同步卫星仅此一家。主要用于观测气象的，即使以后还会发射，八成还是太平洋这个位子或者大西洋上空。
>

bitdust在V2EX上的回复

**Comment by bruce55** [comment]
其实可以切换成日本地区，不过那个是map出来的
