### ISSUE TITLE
公司网络有代理问题

### ISSUE THREAD

**Issue by ll121121** [bitdust/EarthLiveSharp#12]
路径的形式不合法。[latest_address]  [image_path] C:\Users\z208209\EarthLiveSharp\images\5.png

公司全局网络走代理，上网也经常蹦出那个输用户名密码的框，可能中枪了

**Comment by bitdust** [comment]
看来是，获取地址的那一步出问题了。我估计是公司的系统返回了一个空的值，而我的代码里没有判定数据的有效性。我会修一个的

**Comment by bitdust** [comment]
留个邮箱？我给你编译了一个新的试试

**Comment by ll121121** [comment]
liang.li@zf.com
非常感谢！

**Comment by bitdust** [comment]
已发~只是凭猜测做的修改。所以。。。运气好的话也许能行？

**Comment by sunbuny** [comment]
sunbuny@163.com 同样状况 
谢谢
