### ISSUE TITLE
[重要] 关于流量即将耗尽的通知以及应对办法

### ISSUE THREAD

**Issue by bitdust** [bitdust/EarthLiveSharp#13]
情况说明
---
目前这个工具正在使用Cloudinary的CDN作为图片缓存，以免对 向日葵-8 的官网造成流量压力，以达到延长API寿命的目的。
这个工具的火爆程度超出了我的预计，甚至冲上了github的C# trending榜首。在此必须感谢大家的鼎力支持。然而这带来的一个副作用就是我的CDN账户已不堪重负，如下图所示，最高峰时已达到 26GB/天 ！即使我在1.1版本中紧急增加了负载均衡功能依然是杯水车薪。
![clipboard02](https://cloud.githubusercontent.com/assets/6072743/11863727/4ac0dbca-a4d1-11e5-8408-0ebbc467f39a.png)
而我并不能负担如此高的开销，之前计划使用VPS做反向代理的计划也因意外而搁浅。（某B开头的VPS服务商因为我填写的个人资料不完整而封停了我的帐号，233）。
总之，按当前情况来看，Cloudinary迟早会因为流量爆炸而封停封停我的帐号，到时所有客户端将不能正常更新图片。

解决方案1
---
进入Settings窗口，切换图片源为orgin。  
但是个人非常不推荐这个办法， 因为如果大家都这么做的话，会给官方造成很大的流量压力和困扰。很可能导致API被封锁。

解决方案2
---
申请使用私有的CDN账户。按照曾经的估算，一个Cloudinary的免费CDN账户可以支撑10个人不间断的24小时图片抓取。因此如果有能力的话，使用个人的CDN帐号可以一劳永逸的解决这一问题。
具体步骤如下：
1.前往Cloudinary官网注册账户。
记录你的Cloud name
![clipboard04](https://cloud.githubusercontent.com/assets/6072743/11863880/e20f88e0-a4d2-11e5-9254-1825eedca37c.png)

2.编辑你的EarthLiveSharp.exe.Config文件
将 CDN 或CDN1、CDN2、CDN3、CDN4 键值对应的红框所圈中的内容**全部都**修改为你的Cloud name 即可。
![clipboard03](https://cloud.githubusercontent.com/assets/6072743/11863915/2d3acf78-a4d3-11e5-8f0e-e66bec4be064.png)

附言
---
最后还想说点什么，做这个程序只是处于排解近来压力的个人爱好。但是盗用他人API总归是一个不道德行为，现在爆掉了自己的CDN也是一个报应吧！开源软件的意义在于分享自己的喜悦和成果，而非免费的使用别人的服务。可惜自己代码写的又很糟糕，没有什么学习价值，所以这个项目到头来的存在意义就只是骗了200个星星而已。233~
总之呢就是，对自己的任何行为都要负责，不要做慷别人之慨，替别人“开源”。
随着流量耗尽，这个项目可能就要暂停一个段落了，当然出了什么严重bug的话我还是要负责去修的。  
最后再次感谢大家支持！

**Comment by bitdust** [comment]
占位写英文的

**Comment by spin6lock** [comment]
能不能用bt模块做分发啊？你的CDN同时作为tracker，让用户互相分享一下照片

**Comment by bitdust** [comment]
@spin6lock 有趣的想法。
这个和ed2k以及bt并不一样，需要在10分钟内完成对所有用户的数据分发。很类似当年的P2P视频直播，需要发送的是图片流，不过也并不需要太强的实时性和带宽。。。
唔，应该会很有用的东西，而且现在还没有。
可是这应该是远远超过桌面壁纸小工具的项目了，无论是难度上还是任务量上。

**Comment by youxiachai** [comment]
注册教程贴上邀请链吧，这样应该能提高你账号的额度？

**Comment by lizy14** [comment]
不是类似，它本质上就是。。帧频很低的视频直播。。。

我觉得可以一搞，除了日本这个向日葵8号的全彩图，还有一些别的资源可以用来做动态更新的桌面壁纸，比如说除了天上的卫星，

*[北京气象铁塔](http://159.226.97.116/)

甚至一些实时数据的可视化结果，当然就没有那么炫酷了。。

**Comment by bitdust** [comment]
@lizy14 还能发掘出更多的需求吗？（而不只是更新壁纸的）
说起来这个叫EarthLive而不是 himawari-8 live的原因就是想到以后可能去抓其他源的图片~
不过之后就被流量问题教训了。
现在看来P2P的（准实时）推送系统就很重要了

**Comment by Bustycat** [comment]
如果先把图像转成JPEG再发布应该能节省不少流量。

**Comment by bitdust** [comment]
@Bustycat 然而图片转换操作也需要配额~一个月只能进行7500次操作

**Comment by spin6lock** [comment]
这个可以自己在vps上完成吗？毕竟转换操作频次不高，也有现成的库可以做
bitdust <notifications@github.com>于2015年12月22日 周二20:38写道：

**Comment by bitdust** [comment]
应该能节省流量，但是又需要一套脚本~和VPS，并且我相信大家对图像二次压缩都有抵触吧。
最后我现在不打算背流量这个锅了，现在只是提供程序，如果想安心使用的话，还是去自己申请个CDN也一点不麻烦的。

**Comment by Bustycat** [comment]
谁抄谁？
http://www.oxo.ooo

**Comment by cyoncan** [comment]
希望大家都可以申请自己的cdn,不希望官方吧API封锁了.

**Comment by sorz** [comment]
CloudFlare 能解决吗

**Comment by bitdust** [comment]
@sorz 
因为Cloudinary更方便

**Comment by Sean-Pearce** [comment]
请问如何更改图片分辨率呢？看起来好小啊。。。

**Comment by xingrz** [comment]
@bitdust 其实（如果我没理解错的话）方案 2 对官网产生的流量并没有减少，只是经过了 Cloudinary 中转而已。

----------

@Bustycat OXO 那个是我做的，但不会给官网增加压力。我的服务器每 10 分钟会以 4d 分辨率从官网抓取图片后合并保存到我自己的七牛 CDN 空间里，之后客户端的流量全部都是打到七牛上的（同时因为七牛支持 WebP 压缩所以能给客户端节省很多流量）。然而，因为这些都是个人承担的真金白银的流量支出，请原谅我并不能将我的七牛地址公布出来。

**Comment by momoca** [comment]
我不明白显示图片可以从网(http://himawari8.nict.go.jp/)上自游下载.为什么你要转到空间上另存一份呢?
是原站有限制吗?

**Comment by bitdust** [comment]
@xingrz 哇，馒头地球的作者！
这个也是个CDN的抓取接口。图片是会被自动缓冲到CDN里的。
所以流量压力在CDN这里就已经被截住了。

@momoca 如上所说，是为了截住流量，不给源服务器太大压力。

**Comment by xingrz** [comment]
@bitdust 意思是说 Cloudinary 其实是有全局的缓存，即便在不同的帐号里？

**Comment by bitdust** [comment]
@xingrz 是的，他的缓存是全局不分账户的。
顺便一问，你大概在CDN上投了多少钱啊？

**Comment by xingrz** [comment]
@bitdust 还没月结（但也快了，今天31号了）所以具体还不知道

但这几天也是一天烧个20G左右…七牛是前10GB免费，后面0.29元/GB…上线到现在已经烧了120G…

不过还好，本身 WebP 的体积就比 PNG 要小个 90%…

**Comment by bitdust** [comment]
@xingrz 明白了
不过这么看来，WebP果然厉害！

**Comment by xingrz** [comment]
@bitdust 我看了一下 Cloudinary 似乎也支持 WebP 的，可能可以帮你节省不少下载流量。

**Comment by bitdust** [comment]
@xingrz 嗯，有机会试试。

**Comment by momoca** [comment]
@bitdust 谢谢你的解答.

**Comment by ky0ncheng** [comment]
準備一台VPS，利用api拉取himawari8.nict.go.jp的圖片，然後將這些圖片git push到coding/oschina的git服務上，利用raw外鏈出來。

**Comment by xingrz** [comment]
@ky0ncheng 这种做法是可耻的

**Comment by ky0ncheng** [comment]
raw url 既然存在，那存在的意義就是如此。

感謝道德高地。

**Comment by xingrz** [comment]
~~感謝道德高地。~~

还记得当年12306抢票插件拖垮 GitHub 的事件么… 😓

**Comment by bitdust** [comment]
@xingrz 
嗯，我也觉得使用git做分发不是个好方案，而且必然不稳定的风险很大。
刚好看见你路过，顺便一提，你家馒头地球的有时候会变黑白照片。而且似乎不是官网的原因。因为我抓的图片有时候是彩色的同时馒头地球的却是黑白的。有点怀疑是你的CDN转码的原因。
算了，要不等我找的证据再说。。。

**Comment by xingrz** [comment]
@bitdust 谢谢

**Comment by alalalading** [comment]
除了550x550的，还有什么分辨率，电脑上看着有点糊
