### ISSUE TITLE
弹窗报错

### ISSUE THREAD

**Issue by Iamanorange** [bitdust/EarthLiveSharp#14]
![qq 20151219225614](https://cloud.githubusercontent.com/assets/6018925/11913588/b96157a2-a6a3-11e5-9d1d-22c186207560.png)
桌面壁纸没变
EarthLiveSharp 再也没法正常运行

抱歉误删了log。。。

**Comment by lizy14** [comment]
算了吧，目测是日本气象厅官方的网站已挂，估计是越来越火爆形成了一波DDNS。

**Comment by lgp0509** [comment]
可以换个地址吧 好多气象组织的网站都有 我就是不会代码=。= 隔行如隔山啊

比如
agora http://agora.ex.nii.ac.jp/digital-typhoon
CIRA http://rammb.cira.colostate.edu/

**Comment by bitdust** [comment]
@Iamanorange 如果没猜错的话，现在你已经打不开日本方面的官网了。
我这里也不能更新了，应该是官网接口已跪。
@lgp0509 这些网站的图片观赏性不大，而且并不是针对公众的服务（更多是作为科研意义）。所以如果一不小心也把人家给DDOS了，那就太罪过了。

**Comment by Iamanorange** [comment]
已经打不开日本方面的官网了。。。

**Comment by lizy14** [comment]
Here's an alternative: [digital-typhoon.org](http://agora.ex.nii.ac.jp/digital-typhoon/himawari-3g/full-disk.html.en)

update every 30 minutes. 

![image](https://cloud.githubusercontent.com/assets/9985286/11917981/bf00fd6a-a758-11e5-97fd-db4227017d1b.png)

http://agora.ex.nii.ac.jp/digital-typhoon/himawari-3g/latest/Hsfd/RGB/latest.jpg

cloudinary can help you remove the text in the corners, if they annoy you. say, 

![image](https://cloud.githubusercontent.com/assets/9985286/11917985/df7b52d4-a758-11e5-9fb7-c9dda8c0bd81.png)

http://res.cloudinary.com/nullspace/image/fetch/w_550,h_550,r_max,b_black/http://agora.ex.nii.ac.jp/digital-typhoon/himawari-3g/latest/Hsfd/RGB/latest.jpg

note that this site also provides automatically updated [wallpapers](http://agora.ex.nii.ac.jp/digital-typhoon/wallpaper/).

**Comment by lgp0509** [comment]
前天已经自己百度下个VS 连蒙带猜改成agora的那个了
但是人家是不定期更新...

**Comment by bitdust** [comment]
不错的接口~准备做下一次挂掉的备用方案
