### ISSUE TITLE
无图片素材

### ISSUE THREAD

**Issue by byqii** [bitdust/EarthLiveSharp#15]
下载后按照步骤点击，可是image文件夹里没有图片，请问如何解决

**Comment by lizy14** [comment]
@byqii 首先配置文件里默认写的几个的 CDN 已经失效了，见 #13 ；其次因为现在向日葵8号的照片火爆起来了，其官网也撑不住了，不时会挂。

**Comment by byqii** [comment]
现在文件夹里有一张照片，我放上去了，发现桌面一样可以更新实时更新

**Comment by bitdust** [comment]
@byqii 唔，你是不是看那个教程了？那个已经过时了。
现在程序可以直接设置桌面背景，只要点下start就可以了。（如果下载图片没问题的话）

**Comment by byqii** [comment]
不懂欸，不知道你说的教程是哪个，反正可以用就好吧
