### ISSUE TITLE
How to set a live wallpaper?

### ISSUE THREAD

**Issue by bitdust** [bitdust/EarthLiveSharp#2]
TODO
refer to [this issue](https://github.com/bitdust/EarthLiveSharp/issues/3)

**Comment by imsnoo** [comment]
但是win10不能设置间隔时间为10s 
最少就1分钟 怎么办？

**Comment by bitdust** [comment]
@imsnoo 没办法

**Comment by mouism** [comment]
Win可以直接对注册表下手嘛
HKEY_CURRENT_USER\Control Panel\Personalization\Desktop Slideshow里面的Interval的值

**Comment by fineemb** [comment]
@mouism 谨慎使用这个方法。win10更改这个注册表项会改变资源管理器的刷新频率。如果设置成10s，你在文件夹浏览文件的时候超过10s就会自动刷新，回到顶部。
