### ISSUE TITLE
关于流量耗尽的问题

### ISSUE THREAD

**Issue by shoaly** [bitdust/EarthLiveSharp#20]
其实可以在这个repo 大家一起维护一个 cnd.txt, 
这样大家可以pull request 贡献多个免费的 cloudinary出来, 然后程序随机读取就行了

**Comment by bitdust** [comment]
这个项目太小了，只是个人兴趣，所以只提供代码/工具就好了。图片抓取服务什么的不是责任范围内的东西。
还有就是真心喜欢这个壁纸的话，花五分钟注册个帐号也不麻烦~自己使用自己的服务也没有任何道德or法律风险。而如果分享出来，大家一起用的话，就有滥用CDN服务接口的嫌疑了。
总之，这么说吧：程序归程序，服务归服务。

**Comment by CzBiX** [comment]
而你把 origin 放在选项里就没有滥用了吗？

**Comment by bitdust** [comment]
@CzBiX 
那个是万不得已的备份方案。咱们没有和向日葵官网商量，偷用人家的API，不管多大流量，其实都是不道德。只能说尽力不给人家添麻烦了。

**Comment by CzBiX** [comment]
@bitdust 
想想都知道“花五分钟注册个帐号”对大多数人来说意味着什么。
所以我建议你将这个选项删除，强制用户输入 CDN 地址。
真心喜欢这个壁纸的话，自然会花这5分钟。

**Comment by bitdust** [comment]
@CzBiX 明白你的意思了

**Comment by Doracoin** [comment]
确实，还是把“origin”选项去掉吧，我就挺喜欢这个应用的，别再被和谐了。
