### ISSUE TITLE
关于更新至2.0后仍无法使用问题

### ISSUE THREAD

**Issue by byqii** [bitdust/EarthLiveSharp#22]
按照contributor的做法后将代码更换，更换后点击start后仍无反应，但程序setting里已经显示v2.0版本了，问题出在哪？

**Comment by bitdust** [comment]
可以贴下错误日志。在trace.log文件里
因为目前我这里一切正常

**Comment by a2010115** [comment]
你好~问下向日葵8的接口地址在哪里？谢谢！

**Comment by bitdust** [comment]
留个邮箱吧～我发给你

**Comment by byqii** [comment]
![d](https://cloud.githubusercontent.com/assets/16381384/12296183/0fdc3bd2-ba41-11e5-88e4-f187a4ede7b5.png)
 这样吗？

**Comment by bitdust** [comment]
@byqii 
你的问题是原有的CDN账户全部不能用了

可以参照
https://github.com/bitdust/EarthLiveSharp/issues/13
这里的说明，注册并修改CDN帐号。记得验证邮箱信息。

**Comment by byqii** [comment]
ok,搞定啦，谢谢contributor~
