### ISSUE TITLE
The “png” Image can`t be selected in win10

### ISSUE THREAD

**Issue by pealpool** [bitdust/EarthLiveSharp#25]
With the "Slideshow" mode, Images is ".png" In the "images" folder.
But the Background picture just allow us select ".jpg". 
How to do ?

**Comment by pealpool** [comment]
原来不用写英文的，，，，，win10 不能选 png 格式做壁纸，咋整

**Comment by bitdust** [comment]
我能对微软说脏话吗。。
好吧，暂时无解。等下个版本我会试着导出一份jpg格式的图片的。
