### ISSUE TITLE
Support larger image resolution

### ISSUE THREAD

**Issue by Zero3** [bitdust/EarthLiveSharp#27]
Nice application! The image is a little small on my 1080p desktop resolution though. Perhaps you could add support for larger images? It seems like larger resolution images are available as tiles, based on a little URL hacking:

Example of the small size you use at the moment:
http://himawari8-dl.nict.go.jp/himawari8/img/D531106/1d/550/2016/01/28/133000_0_0.png

Example of a larger version of the same image:
http://himawari8-dl.nict.go.jp/himawari8/img/D531106/2d/550/2016/01/28/133000_0_0.png
http://himawari8-dl.nict.go.jp/himawari8/img/D531106/2d/550/2016/01/28/133000_0_1.png
http://himawari8-dl.nict.go.jp/himawari8/img/D531106/2d/550/2016/01/28/133000_1_0.png
http://himawari8-dl.nict.go.jp/himawari8/img/D531106/2d/550/2016/01/28/133000_1_1.png

**Comment by bitdust** [comment]
thanks
i will add this feature in the next release.
