### ISSUE TITLE
更新到2.0版本后无法下载图片

### ISSUE THREAD

**Issue by zx563147474** [bitdust/EarthLiveSharp#28]
Hi你好，我今天把earthlivesharp更新到2.0版本后桌面背景不再变化了，我看了下文件目录里的trace文本，貌似是不能连接到服务器：
[get latest address] {"date":"2016-04-10 04:10:00","file":"PI_H08_20160410_0410_TRC_FLDK_R10_PGPFD.png"}
The remote server returned an error: (401) Unauthorized.[latest_address] http://res.cloudinary.com/divezagkn/image/fetch/http://himawari8-dl.nict.go.jp/himawari8/img/D531106/1d/550/2016/04/10/041000_0_0.png [image_path] D:\EarthLiveSharp\images\0.png
请问您知道这是什么原因吗，谢谢。

**Comment by bitdust** [comment]
你需要参照这个教程进行一些配置：
https://github.com/bitdust/EarthLiveSharp/issues/13

**Comment by guoyanfei-10** [comment]
Hi你好，我今天把earthlivesharp更新到3.0版本后桌面背景不再变化了  images文件夹里也会下载图片不过一次是五张，前四张是每张都是地球的4分之一，第五张是完整的地球。还有一个问题就是用2.0版本正在使用的cloudinary帐号名字也会出现跟上面一样的情况，配置啥的全是按照你的教程来的

**Comment by bitdust** [comment]
@guoyanfei-10 一次下五张是正常情况。因为你设置图片质量为1100*1100了，这样会利用四个图片拼出一个大图。
桌面背景不再变化？这个能告知下你的系统版本，以及贴下EarthLive#时的trace.log吗？

**Comment by guoyanfei-10** [comment]
[我用的是3.0的版本，存放图片那个文件夹有图片还是五张，就像你说的那样四张合成一张，但是桌面背景不会变。3.0的我现在又删了我又重新用回2.0了，昨天中午我的2.0突然间桌面背景不会变了，（今天我才查明原来是我的cloudinary网盘存满了被停用了，我也看不懂英文不会启用我又用别外一个邮箱申请了个帐号现在2.0的又可以用了）看看了您的主页还却实有更新了呢我就下载3.0了，根据您的教程也设置好了，可以出现连接不上服务器的问题（一串英文和软件存放的位置，现在我也知道是cloudinary被停用的原因了）我又换个cloudinary帐号放图的文件夹会下载图片了可是桌面不会变！trace.log文件是压缩包里解压后没动过的！最后想说一声大神你这个软件实在是太帅了！！
[trace.txt](https://github.com/bitdust/EarthLiveSharp/files/417852/trace.txt)

**Comment by guoyanfei-10** [comment]
系统版本是WIN7

**Comment by bitdust** [comment]
@guoyanfei-10 
明白了，我找个win7环境试一下
