### ISSUE TITLE
批量删除cloudinary中存储的图片

### ISSUE THREAD

**Issue by woaihsw** [bitdust/EarthLiveSharp#29]
经过几个月坚持不懈的使用...

我自己cloudinary免费套餐中2G的存储终于爆掉了...一万多张图放在那里...

请问能否提供批量清空cloudinary中过期图片的办法...

或者在earthlivesharp中每使用一幅图片就自动删除cloudinary中上次使用的图片...

**Comment by bombvstnt** [comment]
我也遇到这个问题了，请问有没有简单点的批量删除方法？谢谢！

**Comment by woaihsw** [comment]
@bombvstnt 我是后来写了个nodejs脚本放到vps上每个月删一次...

用cloudinary提供了批量删除的api...

type用fetch就删干净了...

**Comment by a867** [comment]
@woaihsw 请问能分享一下批量删除教程吗？小白完全不懂，现在云盘要停号了。。

**Comment by Doracoin** [comment]
目前还不懂C#，不明白这个项目的原理和实现思路，用Cloudinary的思路是什么？可以接入其他云存储吗？可以的话我想自己改一改，望楼主解惑。

**Comment by bitdust** [comment]
@Doracoin 留个邮箱的话，我可以把接口给你。
用Cloudinary是为了提高连接速度，毕竟CDN提供商的网络会很好，并且降低对日本方面卫星图片服务器的压力。

**Comment by 948171624** [comment]
@bitdust 请问使用过的cloudinary帐号会被共享给他人使用吗？我已经几个月没用的一个私人帐号，最近每天都有卫星图像的增加。另外能否请您发一份教程或自动脚本，方便不会使用官方api的大家删除cloudinary的照片吗？

**Comment by bitdust** [comment]
@948171624 不会的，也许是你不小心把key泄露了，比如给别人拷了自己的软件什么的。。
不过没关系，首先你可以在控制台里禁用自己的帐号。其次，这个账户申请太容易了，不行就再申请就可以了。
确实有办法。。但是比较麻烦，可以说比注册个新账号都麻烦。我之后打算做个小工具供大家用。。不过什么时候能做出来就不一定了。

**Comment by Doracoin** [comment]
@bitdust 916692273@qq.com 感谢分享

**Comment by creke** [comment]
I can help you guys out. But I'm not so familar with git and C#. I'm working on it :)
我可以帮助大家加上自动清理的功能，不过我不太熟悉git和C#。我来撸一下:)

**Comment by bitdust** [comment]
@creke 太好了
你的方案是？
根据我的初步了解，其实是发送指定格式的RESTful请求就可以了。。
如果不熟悉C#的话，可以用些松耦合的方案，不一定集成在主程序里。。比如一个提供用户界面发送RESTful请求的静态页面也很好

**Comment by creke** [comment]
@bitdust 
我用python写了一个批量清理的脚本，有服务器的朋友们，可以在服务器上搞个定时任务。
为了大家方便，顺便编译成了Windows可执行文件：
https://gist.github.com/creke/c5a8a18fa41b8f5c1a0719a7e0cf4de6

**Comment by bitdust** [comment]
@creke 赞！

**Comment by Doracoin** [comment]
gist.github访问不了，只能翻墙了嘛？

**Comment by creke** [comment]
@Doracoin 
命令行下定位到目录并运行，使用参数：
EarthLiveCleanCloudinary [api_key] [api_secret] [cloud_name]
比如你的api_key是123123123，apk_secret是IiIiIiIi，你的云的名字是asdf
则在命令行运行：
EarthLiveCleanCloudinary 123123123 IiIiIiIi asdf

**Comment by Doracoin** [comment]
感谢，已解决

**Comment by p0we7** [comment]
@creke  程序坏了
