### ISSUE TITLE
如何设置为动态的桌面背景？

### ISSUE THREAD

**Issue by bitdust** [bitdust/EarthLiveSharp#3]
1. [下载程序](https://github.com/bitdust/EarthLiveSharp/releases)并运行
2. 点击 start 按钮  
![clipboard05](https://cloud.githubusercontent.com/assets/6072743/11613262/b6046e8a-9c55-11e5-8ce5-7f9f56083411.png)
3. 在桌面右键菜单选择 个性化   
![clipboard08](https://cloud.githubusercontent.com/assets/6072743/11613266/c5556a7e-9c55-11e5-9ad2-871eeb5658b0.png)
4. 进入 桌面背景 菜单  
![clipboard09](https://cloud.githubusercontent.com/assets/6072743/11613269/d31ec36c-9c55-11e5-97d0-acd779de60d9.png)
5. 浏览至保存图片的文件夹（默认为 EarthLiveSharp/images 文件夹）  
![clipboard0111](https://cloud.githubusercontent.com/assets/6072743/11613270/dcfddefe-9c55-11e5-84b5-3f952ff4cac6.png)
6. 当看到有至少两张图片时，点击全选按钮。（这是一个windows的小技巧，点击全选后，文件夹中所有图片，包括新增的图片，也会被设置为桌面背景）  
![clipboard0112](https://cloud.githubusercontent.com/assets/6072743/11613271/e523a078-9c55-11e5-8e6e-2c5de69fc8f7.png)
7. 选择图片放置方式为 居中 ， 背景颜色为 黑色 ，更改图片间隔调为 10s。  
![clipboard0113](https://cloud.githubusercontent.com/assets/6072743/11613273/ec4f91ea-9c55-11e5-844f-dfbe525ba339.png)
8. 点击保存更改即可。  
![clipboard0114](https://cloud.githubusercontent.com/assets/6072743/11613274/f27b9d0c-9c55-11e5-8180-0d7badf0d4b7.png)  

效果如下图所示：
![clipboard0156](https://cloud.githubusercontent.com/assets/6072743/11613290/6af013a8-9c56-11e5-8d7e-553cc8226d5a.png)

**Comment by bitdust** [comment]
![clipboard0156](https://cloud.githubusercontent.com/assets/6072743/11613313/8b2ef4da-9c57-11e5-8b3d-39bc61a4846e.png)

顺便一提，其实你可以用这张壁纸当作桌面时钟来用：  
* 用晨昏线位置估计当地时间；  
* 用太阳入射角度估计四季变化即日期。  

是不是超赞？

**Comment by SilentDepth** [comment]
这样是让Windows循环刷新文件夹下的图片，并不是实际意义上的「实时」？

**Comment by bitdust** [comment]
@SilentDepth 
哇，第一个issue诶
由于理解歧义，我还不清楚你的担心具体是哪个，所以就把自己的考虑全说出来吧：
1.如果你担心桌面背景不会随着图片刷新而刷新，那是多虑了。只要你在第6步中点击“全选”按钮的话。那个选中文件夹所有的更新都会被刷到桌面背景上。甚至新增的图片也会被设置成背景。
2.如果你担心以slideshow方式展示图片的方法不够实时。这个的确是，我的考虑是这样的：官网的图片刷新间隔是10分钟；默认的检查间隔为7分钟；桌面的切换间隔是10秒钟，默认保存5张图片。因此最坏情况，你也能在10s+7min+50s=8分钟内看到最新更新的图片，考虑到官方更新间隔为10min的话，我觉得这个指标足够了。
如果你想要更好的实时性的话，可以调低最大图片数量为2，检查间隔为5min。这样任何时候，你都能看到最近20分钟内的地球照片啦！

另外，这个工具我是用过一段时间了。一些参数也是总结出来的。为什么要用slideshow方式展示？因为这样可以让桌面显得不那么单调。如果有人好奇你的桌面背景是什么的话，你可以让他盯着背景看10秒钟，他就会发现：我去，这个地球真的在动诶 o(≧v≦)o~~
如果他还不相信这是实时图片的话，你就可以跟他普及下晨昏线与当地时间的关系咯。

**Comment by SilentDepth** [comment]
嗯，1.0正式版实现了最新照片设置为桌面背景的功能，这样好多了
程序根目录多了个wallpaper.bmp，是这个功能产生的？

**Comment by bitdust** [comment]
@SilentDepth  的确如此~

**Comment by Kenshin** [comment]
Hi，我之前在V2EX上面留过言（85楼~）， 方便的话，请告知API调用方式，我会把它加到SimpTab的下个版本中。 :)

**Comment by bitdust** [comment]
@Kenshin 已发

**Comment by xyangk** [comment]
我写个[python文件](https://github.com/xyangk/EarthLiveSharp),可以在ubuntu运行并自动更换壁纸.

**Comment by imsnoo** [comment]
但是win10不能设置间隔时间为10s 
最少就1分钟 怎么办？

**Comment by SilentDepth** [comment]
@imsnoo 不怎么办，因为图片源的更新频度比这个慢得多 XD

**Comment by marginDelta** [comment]
@bitdust 从trace.log里看 一直出现 The remote server returned an error: (401) Unauthorized. 是什么情况?我用的是v2.0 似乎EarthLiveSharp只会在点start之后 正确download图片, 之后每隔7分钟的自动更新 统统都是Unauthorized 0. 0
应该并不是真的无法 access 图片服务器, 看过 source code 的亲知道怎么解决么

另外 在v2.0里 即便选了 slideShow mode, 好像并没有把windows背景图片设为 image文件夹, 这个算是bug...?

**Comment by marginDelta** [comment]
除了程序问题 我还想问一个物理问题... 
这个日本向日葵网站提供的卫星图片是通过同步卫星拍摄的吧, 看上去好像这个同步卫星是对着澳大利亚+大西洋的, 是不是因为政治问题 不能提供其他位置 (比如:东8区附近) 同步卫星的照片? X. X

**Comment by marginDelta** [comment]
v1.0 似乎没有定期update unauthority的问题
有人愿意一起修正v2.0里面的问题 我也可以一起参与看code (没人 我也就凑合着偷懒了 手动滑稽), 虽然我有点讨厌cShape 找个函数实体每次都global search得妈都不认得, 让我这种从来不打tag的ultraEdit用户情何以堪... 233

**Comment by bitdust** [comment]
@marginDelta (401) Unauthorized. 的问题，似乎是你的cloudinary帐号没有验证邮箱？
至于角度问题，那是因为卫星确实只固定在了澳大利亚上空，并不是政治问题。

**Comment by marginDelta** [comment]
@bitdust 我还没注册cloudinary账号 但v1.0已经work一天了, v2.0的unauthority多数跟cloudinary没关系 毕竟点start的那一瞬间 v2.0也是能抓到图的
当然 我在setting里选的都是org 没有选cdn, 因为如果选cdn就完全download不到图片了 目测选cdn source可能跟cloudinary有关

那么只有这一颗卫星可以用咯 理论上现在这个年代各国家应该在赤道上空布满同步卫星才对 不要那么小气嘛 233

**Comment by ZhengweiHou** [comment]
@bitdust 
您好，我想请教一下
http://himawari8-dl.nict.go.jp/himawari8/img/D531106/1d/550/2016/08/05/031000_0_0.png
这张图片路径中的031000_0_0是什么意思，表示时间么，时间间隔怎么算

**Comment by bitdust** [comment]
@ZhengweiHou
你可以留下邮箱，我把接口发给你

**Comment by ZhengweiHou** [comment]
@bitdust 916108538@qq.com

**Comment by bitdust** [comment]
@ZhengweiHou 已发

**Comment by rpker** [comment]
？？？？？？/

**Comment by EnochZhangY** [comment]
你好，我start之后电脑背景就变成全黑，也不出现地球的图片，images文件夹里也没有下载的图片，在trace文件中提示远程服务器返回错误: (404) 未找到。可以请教怎么处理这个问题吗？
![1599227808(1)](https://user-images.githubusercontent.com/70733746/92247359-b8a04500-eef9-11ea-9c94-539b5aeb9541.png)

**Comment by Andreby42** [comment]
cdn 填写有问题吧 建议检查下

**Comment by EnochZhangY** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "郭大路"<notifications@github.com&gt;; 
发送时间: 2020年9月5日(星期六) 下午2:48
收件人: "bitdust/EarthLiveSharp"<EarthLiveSharp@noreply.github.com&gt;; 
抄送: "张颖"<1057492709@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [bitdust/EarthLiveSharp] 如何设置为动态的桌面背景？ (#3)





 
cdn 填写有问题吧 建议检查下

**Comment by EnochZhangY** [comment]
> 
> 
> cdn 填写有问题吧 建议检查下
哇，收到回复太激动了
我一开始也以为是cdn的问题，就使用origin方式，也是没有反应的。
setting里面的参数我也是一个一个试过了，并没有变化。
后来start几次之后发现原文件夹会出现一个trace.log文件。
我打开看了一下，显示远程服务器返回错误: (404) 未找到。
能不能帮我看一下这是什么问题呢？
![1599229324(1)](https://user-images.githubusercontent.com/70733746/92299885-057f2c80-ef89-11ea-8f8b-d8575c0f9fb5.png)
![1599229350(1)](https://user-images.githubusercontent.com/70733746/92299887-07e18680-ef89-11ea-9a18-047529cb6e11.png)
![1599229382(1)](https://user-images.githubusercontent.com/70733746/92299889-0912b380-ef89-11ea-83e9-deb2cd176075.png)

**Comment by Andreby42** [comment]
图像抓取源那个 选CDN（推荐选项）

**Comment by EnochZhangY** [comment]
一开始尝试选择CDN,账号也注册了，然后start是说远程服务器404错误。
怀疑是不是CDN有问题，就尝试了用origin方式抓取图片源，trace文件还是出现远程服务器404错误。
所以我想是不是其他地方有问题了，还没找到解决办法。

**Comment by Andreby42** [comment]
我试下最新的版本

**Comment by EnochZhangY** [comment]
对哦，那我也去试试之前的几个版本
说不定是我的电脑问题

**Comment by Andreby42** [comment]
你可以新开issue了 兄弟

**Comment by EnochZhangY** [comment]
先解决了再说吧
我下载了3.0的也不行
我准备每个版本试一下

**Comment by EnochZhangY** [comment]
我试了一下3.8版本的
trace文件
[himawari8 connection error]
但是那个向日葵的网站我能打开，也是实时的，这又是为啥呢
心态崩了

**Comment by Andreby42** [comment]
这你得问作者了 代码应该在dll文件里



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Enoch"<notifications@github.com&gt;; 
发送时间: 2020年9月5日(星期六) 下午3:31
收件人: "bitdust/EarthLiveSharp"<EarthLiveSharp@noreply.github.com&gt;; 
抄送: "38912428"<38912428@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [bitdust/EarthLiveSharp] 如何设置为动态的桌面背景？ (#3)





 
我试了一下3.8版本的
 trace文件
 [himawari8 connection error]
 但是那个向日葵的网站我能打开，也是实时的，这又是为啥呢
 心态崩了

**Comment by Andreby42** [comment]
这你得@作者

**Comment by EnochZhangY** [comment]
作者不知道能不能看见，
我去那个issue下面问问
这边也
 @bitdust
