### ISSUE TITLE
How to get the Cloud Name (of cloudinary.com) ?

### ISSUE THREAD

**Issue by bitdust** [bitdust/EarthLiveSharp#32]

**Comment by bitdust** [comment]
施工占楼

**Comment by codexss** [comment]
看起来腾讯云的万象优图也有免费的CDN，并且支持镜像源映射
https://www.qcloud.com/product/ci.html
![image](https://cloud.githubusercontent.com/assets/5959201/18573482/743dfca6-7bf6-11e6-875d-7b77f792d803.png)

**Comment by bitdust** [comment]
@codexss 
刚才试了一下，似乎没有cloudinary注册使用的流程友好。。所以我就不把他加成默认的图片源了。不过我考虑增加一个自定义图片源的选项，来满足有诸君的探索心 😄 。

**Comment by mingyuerujing** [comment]
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.IO.FileNotFoundException: G:\EarthLiveSharp\images\0_0.png
   在 System.Drawing.Image.FromFile(String filename, Boolean useEmbeddedColorManagement)
   在 EarthLiveSharp.scraper.JoinImage()
   在 EarthLiveSharp.mainForm.startLogic()
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   在 System.Windows.Forms.Button.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.6.1080.0 built by: NETFXREL3STAGE
    基本代码:file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
EarthLiveSharp
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///G:/EarthLiveSharp/EarthLiveSharp.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.6.1038.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.6.1081.0 built by: NETFXREL3STAGE
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.6.1078.0 built by: NETFXREL3STAGE
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.6.1038.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.6.1038.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.6.1064.2 built by: NETFXREL3STAGE
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.resources
    程序集版本:4.0.0.0
    Win32 版本:4.6.1038.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.resources.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.6.1038.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.6.1038.0 built by: NETFXREL2
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试器，
而不是由此对话框处理。

**Comment by junliangi** [comment]
cloudinary网址打不开什么鬼，还是我这边代理问题

**Comment by bitdust** [comment]
@junliangi 我这里没问题
不行切orgin暂时用着

**Comment by junliangi** [comment]
@bitdust 邮箱：sdsrzsjxljl@163.com  Thank

**Comment by junliangi** [comment]
桌面不同步应该不是cnd的原因，在Windows里主题切换一下照片又同步了

**Comment by junliangi** [comment]
@bitdust 邮箱：sdsrzsjxljl@163.com  Thank

**Comment by mengzilym** [comment]
是不是要一直打开着软件才能更新壁纸？

**Comment by bitdust** [comment]
@mengzilym 是这样，不过这个小程序会自动随系统启动，后台运行。
而且开销极低，不占内存。

**Comment by wasas** [comment]
这个存图片的网站, 免费的好像只有 2G 空间, 一不小心就满了.. 怎么清空呢?

**Comment by chermy** [comment]
@wasas 联系客服下工单, 之后客服会回复你邮件确认, 回复即可. 最好在晚上操作. 回复很快.

**Comment by wasas** [comment]
@chermy 感谢...
目前使用这位的清空软件 win 版 https://github.com/bitdust/EarthLiveSharp/issues/29
我有 VPS, 路由也能运行一些脚本, 不过没弄明白 py 版本应该怎么使用..

**Comment by Anarky1900** [comment]
setting貌似出了一点问题，只能自己改配置文件。

**Comment by bitdust** [comment]
@Anarky1900 是最新版吗？什么操作出问题了？

**Comment by Anarky1900** [comment]
@bitdust 是的，点CDNsetting的下半部分会消失，没办法填数据。改了配置文件貌似还是不行
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0"/> 
    <supportedRuntime version="v2.0.50727"/>
  </startup>
  <appSettings>
    <add key="version" value="v3.5" />
    <add key="image_folder" value="D:\安装包\EarthLiveSharp\images" />
    <add key="interval" value="10" />
    <add key="autostart" value="True" />
    <add key="size" value="4" />
    <add key="zoom" value="70" />
    <add key="image_source" value="http://res.cloudinary.com/da7lfsmqn/image/fetch/http://himawari8-dl.nict.go.jp/himawari8/img/D531106" />
    <add key="source_selection" value="1" />
    <add key="cloud_name" value="da7lfsmqn" />
    <add key="api_key" value="612948298285481" />
    <add key="api_secret" value="PnE7sNch8fjsVT6fRlwSvmXwvj8" />
    <add key="ClientSettingsProvider.ServiceUri" value="CLOUDINARY_URL=cloudinary://612948298285481:PnE7sNch8fjsVT6fRlwSvmXwvj8@da7lfsmqn" />
  </appSettings>
  <system.web>
    <membership defaultProvider="ClientAuthenticationMembershipProvider">
      <providers>
        <add name="ClientAuthenticationMembershipProvider" type="System.Web.ClientServices.Providers.ClientFormsAuthenticationMembershipProvider, System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" serviceUri=""/>
      </providers>
    </membership>
    <roleManager defaultProvider="ClientRoleProvider" enabled="true">
      <providers>
        <add name="ClientRoleProvider" type="System.Web.ClientServices.Providers.ClientRoleProvider, System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" serviceUri="" cacheTimeout="86400"/>
      </providers>
    </roleManager>
  </system.web>
</configuration>

**Comment by Anarky1900** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0"/> 
    <supportedRuntime version="v2.0.50727"/>
  </startup>
  <appSettings>
    <add key="version" value="v3.5" />
    <add key="image_folder" value="D:\安装包\EarthLiveSharp\images" />
    <add key="interval" value="10" />
    <add key="autostart" value="True" />
    <add key="size" value="4" />
    <add key="zoom" value="70" />
    <add key="image_source" value="http://res.cloudinary.com/da7lfsmqn/image/fetch/http://himawari8-dl.nict.go.jp/himawari8/img/D531106" />
    <add key="source_selection" value="1" />
    <add key="cloud_name" value="da7lfsmqn" />
    <add key="api_key" value="612948298285481" />
    <add key="api_secret" value="PnE7sNch8fjsVT6fRlwSvmXwvj8" />
    <add key="ClientSettingsProvider.ServiceUri" value="CLOUDINARY_URL=cloudinary://612948298285481:PnE7sNch8fjsVT6fRlwSvmXwvj8@da7lfsmqn" />
  </appSettings>
  <system.web>
    <membership defaultProvider="ClientAuthenticationMembershipProvider">
      <providers>
        <add name="ClientAuthenticationMembershipProvider" type="System.Web.ClientServices.Providers.ClientFormsAuthenticationMembershipProvider, System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" serviceUri=""/>
      </providers>
    </membership>
    <roleManager defaultProvider="ClientRoleProvider" enabled="true">
      <providers>
        <add name="ClientRoleProvider" type="System.Web.ClientServices.Providers.ClientRoleProvider, System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" serviceUri="" cacheTimeout="86400"/>
      </providers>
    </roleManager>
  </system.web>
</configuration>`

**Comment by Anarky1900** [comment]
@bitdust 是的，点CDNsetting的下半部分会消失，没办法填数据。改了配置文件貌似还是不行
这里是配置文件
<?xml version="1.0" encoding="utf-8"?> <configuration> <startup> <supportedRuntime version="v4.0"/> <supportedRuntime version="v2.0.50727"/> </startup> <appSettings> <add key="version" value="v3.5" /> <add key="image_folder" value="D:\安装包\EarthLiveSharp\images" /> <add key="interval" value="10" /> <add key="autostart" value="True" /> <add key="size" value="4" /> <add key="zoom" value="70" /> <add key="image_source" value="http://res.cloudinary.com/da7lfsmqn/image/fetch/http://himawari8-dl.nict.go.jp/himawari8/img/D531106" /> <add key="source_selection" value="1" /> <add key="cloud_name" value="da7lfsmqn" /> <add key="api_key" value="612948298285481" /> <add key="api_secret" value="PnE7sNch8fjsVT6fRlwSvmXwvj8" /> <add key="ClientSettingsProvider.ServiceUri" value="CLOUDINARY_URL=cloudinary://612948298285481:PnE7sNch8fjsVT6fRlwSvmXwvj8@da7lfsmqn" /> </appSettings> <system.web> <membership defaultProvider="ClientAuthenticationMembershipProvider"> <providers> <add name="ClientAuthenticationMembershipProvider" type="System.Web.ClientServices.Providers.ClientFormsAuthenticationMembershipProvider, System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" serviceUri=""/> </providers> </membership> <roleManager defaultProvider="ClientRoleProvider" enabled="true"> <providers> <add name="ClientRoleProvider" type="System.Web.ClientServices.Providers.ClientRoleProvider, System.Web.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" serviceUri="" cacheTimeout="86400"/> </providers> </roleManager> </system.web> </configuration>

**Comment by bitdust** [comment]
奇怪~我这里没有复现这个问题。
建议你记录下现有的的设置，然后重新下载个新的程序试试~不要替换配置文件，重新手动设置下

**Comment by Anarky1900** [comment]
> [get latest ImageID] 2017/04/21/143000
基础连接已经关闭: 接收时发生错误。 2017/04/21/143000
[image_folder]D:\安装包\EarthLiveSharp\images [image_source]http://res.cloudinary.com/da7lfsmqn/image/fetch/http://himawari8-dl.nict.go.jp/himawari8/img/D531106 [size]4
可以问一下ClientSettingsProvider.ServiceUri需要填吗？

**Comment by Anarky1900** [comment]
是的，sp4

**Comment by bitdust** [comment]
@Anarky1900 留个邮箱吧~我给你发个新版的测试下

**Comment by Anarky1900** [comment]
@bitdust Surfacepro1900@outlook.com 谢谢:)

**Comment by bitdust** [comment]
@Anarky1900 已发送

**Comment by Anarky1900** [comment]
@bitdust sitting界面没问题了，但是依旧无法获取图片

> get latest ImageID] 2017/04/21/153000
基础连接已经关闭: 接收时发生错误。 2017/04/21/153000
[image_folder]D:\安装包\EarthLiveSharp\images [image_source]http://res.cloudinary.com/da7lfsmqn/image/fetch/http://himawari8-dl.nict.go.jp/himawari8/img/D531106 [size]4

**Comment by Anarky1900** [comment]
orgin是可用的

**Comment by bitdust** [comment]
@Anarky1900 这个问题好奇怪。。
在你的浏览器下，能打开这个链接吗？
http://res.cloudinary.com/da7lfsmqn/image/fetch/http://himawari8-dl.nict.go.jp/himawari8/img/D531106/1d/550/2017/04/21/155000_0_0.png

**Comment by Anarky1900** [comment]
火狐可以，edge不行。看来是我的问题，我再想想办法。

**Comment by bitdust** [comment]
@Anarky1900 可能是你那里网络连接问题。

**Comment by Anarky1900** [comment]
现在可以打开了，依旧接收错误ORZ

**Comment by bitdust** [comment]
@Anarky1900 我谷歌的结果似乎是和HTTP连接数有关~
可能是一直尝试次数过多的原因，那么重启下电脑试试？

**Comment by Anarky1900** [comment]
的确是网络问题，移动的宽带和热点都不行，换成联通就好了。

**Comment by junliangi** [comment]
cloudinary储存满了，有什么可以方便清理掉的方法？

**Comment by bitdust** [comment]
@junliangi 试试新版本，可以自动清理缓存了！

**Comment by junliangi** [comment]
@bitdust 现在我cloudinary已经存满了用3.5以上的版本可以自动清理吗？似乎还是没更新......
![ufnq6e2z0y03 4 hljeym](https://user-images.githubusercontent.com/22606275/27387797-44581182-56cc-11e7-9a02-eee96271740d.png)
![14smv aemp _8jj 2 e4ns](https://user-images.githubusercontent.com/22606275/27387800-48d0b99e-56cc-11e7-8e84-6861ee612d9b.png)

**Comment by bitdust** [comment]
@junliangi 要么发邮件。。不过还是重新申一个吧，花不了5分钟

**Comment by junliangi** [comment]
@bitdust 已经让客服给删除了，新版本是不是会自动删除？

**Comment by bitdust** [comment]
@junliangi 是的，需要多设置些东西，看看上面的说明吧

**Comment by younglamb** [comment]
你好，请问为什么我的软件版本选择了 CDN ，但是没有出现 cloud name 这类的设置呢？截图在这里http://weibo.com/1870601202/Fa8BViVCF?ref=home

**Comment by bitdust** [comment]
@younglamb 你的版本太老了。。从我的release页下载新版本吧

**Comment by junliangi** [comment]
现在EarthLive一直不更新从cdn换到orgin也一样，哪里问题？其他用户也这样吗？
![u3_p_s ber9a17l1gs85](https://user-images.githubusercontent.com/22606275/27769908-84018284-5f67-11e7-8b9c-900471392cf2.png)

**Comment by bitdust** [comment]
@junliangi 最近官方服务器确实有不稳定的现象~并不清楚原因

**Comment by Zhang-Siyang** [comment]
呃，每个人都用自己的CDN，那不还是会给服务器带来很大的压力吗？应该是搭建一个公用的CDN，没人都从上面下载才对呀

**Comment by bitdust** [comment]
@Zhang-Siyang 做过测试，只要有一个用户缓存图片后，其他用户都是从CDN网络中直接获取的最新图片，不会对服务器产生压力。

**Comment by Zhang-Siyang** [comment]
@bitdust 原来是这样

**Comment by Soindigo** [comment]
每次启动都会有这个提示 请问可以关闭吗

**Comment by bitdust** [comment]
@Soindigo 那何不按上面的说明配置一个CDN账户呢？配置完成后就不会提示消息了

**Comment by junliangi** [comment]
不知为什么这几天使用cdn不同步了 只能切换orgin了

**Comment by ZhongXinlin** [comment]
我的不更新了，有谁也遇到这个问题了吗

**Comment by DengMr** [comment]
支持阿里云的对象储存吗？

**Comment by bitdust** [comment]
> 
> 
> 支持阿里云的对象储存吗？

不支持

**Comment by halo67** [comment]
额，用了CDN每次开机还是会跳到这个界面吗

**Comment by bitdust** [comment]
> 
> 
> 额，用了CDN每次开机还是会跳到这个界面吗

亲，用了CDN就不会跳了呢。

**Comment by halo67** [comment]
> > 额，用了CDN每次开机还是会跳到这个界面吗
> 
> 亲，用了CDN就不会跳了呢。

重启过后它确实还是会自动跳转到github。。。

**Comment by halo67** [comment]
> > 额，用了CDN每次开机还是会跳到这个界面吗
> 
> 亲，用了CDN就不会跳了呢。

重启会跳，关机再开机不会跳了

**Comment by Wangzhiran** [comment]
可以，很高清，之前在52下的汉化修改版win10存在兼容问题，谢谢

**Comment by bitdust** [comment]
@Wangzhiran 汉化版不是我做的。。这么个小工具配一次就不用管了，所以个人认为汉化不是很有必要。

**Comment by junliangi** [comment]
最近不知道啥原因显示同步新图像之后刷新几次或者等一会就自动换成这个图像了，以为是版本问题换成最新的还是这样。有跟我一样的嘛
![QQ图片20200712230051](https://user-images.githubusercontent.com/22606275/87249782-b8ed0880-c493-11ea-9200-a638b29fca05.png)

**Comment by EnochZhangY** [comment]
你好作者
我运行3.9的时候会出现远程服务器返回错误: (404) 未找到
再换了3.85老版本时候出现这个问题[himawari8 connection error]
是我的网速问题吗？
运行之前所有的版本都不行，都会出现远程服务器返回错误: (404) 未找到
所以 @ bitdust 
期望你的解答，谢谢

**Comment by doug4567** [comment]
作者你好..突然發現目前資料抓取有問題..我是用CDN做為圖源..不過目前似乎一直抓不到最新的圖..不知道是什麼原因就是了

![image](https://user-images.githubusercontent.com/101128881/157074981-e80c8294-75a9-4dcb-9f6d-6892899570d1.png)

**Comment by EnochZhangY** [comment]
好的，感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bitdust/EarthLiveSharp"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月8日(星期二) 凌晨0:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bitdust/EarthLiveSharp] How to set CDN as the image source? (#32)





 
作者你好..突然發現目前資料抓取有問題..我是用CDN做為圖源..不過目前似乎一直抓不到最新的圖..不知道是什麼原因就是了
 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by doug4567** [comment]
這陣子又無法自動更新圖資了...有好幾天都是這樣的情形
