### ISSUE TITLE
使用最新版3.0，桌面背景并没有变化。

### ISSUE THREAD

**Issue by Doracoin** [bitdust/EarthLiveSharp#33]
我使用的版本是

`   <startup>
    <supportedRuntime version="v4.0"/> 
    <supportedRuntime version="v2.0.50727"/>
  </startup>
  <appSettings>
   <add key="version" value="v3.0" />`
 

image文件夹下的图片确实在更新，但是桌面背景图并没有被设置，是我的使用方法不对吗？

使用环境：
Win7 专业版

**Comment by MNevin** [comment]
我的也是，是不是win7本身的问题

**Comment by bitdust** [comment]
明白，我尽快测试下~

**Comment by halexan** [comment]
我也存在这个问题，win7 64bit，打开以后背景没有变化 @bitdust

**Comment by RainboatD** [comment]
我是手动设置了壁纸更换背景图片，选中的是 \EarthLiveSharp\images 这个文件夹下面的两张图片实现的自动换背景。

**Comment by bitdust** [comment]
唔，在自己电脑上试了试。。居然没有重现这个问题。。尴尬了，我还得多借几台电脑试试。
楼上诸位的选项里都用的 orgin 还是 CDN？CDN配置自己的key了吗？
不然先用 @RainboatD 的办法凑活下

**Comment by bitdust** [comment]
@Doracoin @MNevin @halexan @RainboatD 
在 v3.1 中搞定了。
是我保存的图片格式为了png，但扩展名些成了bmp。在win10下系统可以自动处理这个错误，而win7下不可以。因此我修改了代码就解决了。

**Comment by Doracoin** [comment]
辛苦啦~
