### ISSUE TITLE
版本v3.3 无法获取图片

### ISSUE THREAD

**Issue by halexan** [bitdust/EarthLiveSharp#38]
版本v3.3，报错如下：

``` xml
[get latest ImageID] 2016/10/17/234000
基础连接已经关闭: 接收时发生错误。 2016/10/17/234000
[image_folder]C:\Program Files\EarthLiveSharp-v3.3\images 
[image_source]http://res.cloudinary.com/*******/image/fetch/http://himawari8-dl.nict.go.jp/himawari8/img/D531106 [size]1
```

直接访问
http://himawari8-dl.nict.go.jp/himawari8/img/D531106
提示

> You don't have permission to access / on this server.

感觉图片源貌似不太对？审查元素看到的img src是：

``` xml
http://himawari8-dl.nict.go.jp/himawari8/img/D531106/1d/550/2016/10/18/235000_0_0.png
```

或者

``` xml
http://himawari8-dl.nict.go.jp/himawari8/img/D531106/thumbnail/550/2016/10/18/235000_0_0.png
```

感觉他们网站目录貌似改变了，变成了包含GMT时间的路径，这样图片的网址就成了动态变化的了

**Comment by littleicesnow** [comment]
我的也不行，已经下了最新的V3.3

trace.log显示如下：

[get latest ImageID] 2016/10/18/212000
The underlying connection was closed: An unexpected error occurred on a receive. 2016/10/18/212000
[image_folder]D:\EarthLiveSharp\images [image_source]http://res.cloudinary.com/XXXXXXXXX/image/fetch/http://himawari8-dl.nict.go.jp/himawari8/img/D531106 [size]2

**Comment by halexan** [comment]
@littleicesnow 
你的报错和我的一样

**Comment by littleicesnow** [comment]
@halexan 怎么破呢......图片一直没下载，我确定我的CDN是正常的

**Comment by halexan** [comment]
@littleicesnow 
嘻嘻，我也不会，需要@bitdust 来解决

**Comment by Doracoin** [comment]
如果想用的话，建议先用着3.1，等问题解决了再更新。
3.1我使用了挺久了，没出现大问题，比较稳定。

**Comment by bitdust** [comment]
似乎我这里没有重现这个问题，
你们那个现在还可以用吗？

**Comment by littleicesnow** [comment]
@Doracoin   3.1 我是简直不能启动的，只有3.2  和3.3 能启动，但是图片不更新。

**Comment by littleicesnow** [comment]
@bitdust 还是不行，我用家里三台电脑都试过了，都不行。只能等以后的版本了

**Comment by bitdust** [comment]
@littleicesnow 收到，我继续测试下
主要是我目前不在工位上，在别人电脑用 EarthLive# 3.3 在window10 x64环境下，使用 orgin source工作正常。
有机会测试下更多的环境

**Comment by littleicesnow** [comment]
`<img src="http://i1194.photobucket.com/albums/aa378/littleicesnow/2016/earthop.gif" alt="" width="440" height="330" />`
我怎么就是忘记给你截图了呢。。。。

**Comment by littleicesnow** [comment]
http://i1194.photobucket.com/albums/aa378/littleicesnow/2016/earthop.gif

**Comment by halexan** [comment]
@bitdust 已在[issue#40](https://github.com/bitdust/EarthLiveSharp/issues/40)说明了这个问题，貌似不是图片源地址的问题。
