### ISSUE TITLE
scraper的类型初始值设定项引发异常。

### ISSUE THREAD

**Issue by arckalsun** [bitdust/EarthLiveSharp#39]
你好，我在你的代码上新建了一个项目，之后再调试发生这个错误，这个该怎么解决？
![default](https://cloud.githubusercontent.com/assets/19990356/19674248/60eb54aa-9ab9-11e6-8f00-8027dd89cb76.png)

**Comment by bitdust** [comment]
暂时没有开发环境。。回头我试试，你确定是在使用最新的代码吗

**Comment by arckalsun** [comment]
不是代码问题，是我修改了工程设置，导致错误。已解决。
