### ISSUE TITLE
抓取图片地址已失效

### ISSUE THREAD

**Issue by yduke** [bitdust/EarthLiveSharp#40]
看了下config文件，要抓取的地址是：
`http://himawari8-dl.nict.go.jp/himawari8/img/D531106`
然后这个地址直接访问会403 forbidden
所以无论是原地址还是cdn都无法获取图片。

**Comment by bitdust** [comment]
这个地址本来就是 403 的
程序会自己拼接出来可用的地址,比如：

http://himawari8-dl.nict.go.jp/himawari8/img/D531106/1d/550/2016/10/25/171000_0_0.png
