### ISSUE TITLE
建议： 添加一个Cloudinary 的API操作每个月自动清空图片库

### ISSUE THREAD

**Issue by p0we7** [bitdust/EarthLiveSharp#41]
我自己注册的cloudinary 图片库 前几天收到email说满了让我升级plan 。

官方的API是可以清空图片库的，但是直接手动操作的方法却找不到。

**Comment by bitdust** [comment]
计划中，假期里想想办法~
https://github.com/bitdust/EarthLiveSharp/issues/32
这里似乎有人做了个python脚本，你可以试试

**Comment by bitdust** [comment]
The feature is avalible in [v3.5](https://github.com/bitdust/EarthLiveSharp/releases/tag/v3.5)

**Comment by p0we7** [comment]
@bitdust  感谢明天更新试试.
