### ISSUE TITLE
改时区有用吗,大半夜的想看的明亮的全景呢...

### ISSUE THREAD

**Issue by judgedong** [bitdust/EarthLiveSharp#42]
怎么改时区?

**Comment by judgedong** [comment]
还是要改时间吗?

**Comment by bitdust** [comment]
并没有什么用处。。只是想看全景的话，保存几张你满意的图片，然后手动设置成背景就可以了。

这个工具真正酷的地方就是实时更新，从地球暗面里露出第一缕曙光的时候也很漂亮啊
