### ISSUE TITLE
自己写着玩,对api有一些疑问

### ISSUE THREAD

**Issue by judgedong** [bitdust/EarthLiveSharp#43]
api更新图片的规律是什么,多久能更新一次
11.20的图片最早几点能更新出来
看了官网有这样一个api,是否可以从这里获取当前最新的图片的信息
http://himawari8-dl.nict.go.jp/himawari8/img/D531106/latest.json

**Comment by bitdust** [comment]
是的，我也是用的这个API
大概有不到半个小时的延迟吧

**Comment by judgedong** [comment]
@bitdust 我说怎么改本地时间都没用呢....
