### ISSUE TITLE
想问下为什么用了几周后，现在无法更新葵花8的图像了

### ISSUE THREAD

**Issue by silverbreathing** [bitdust/EarthLiveSharp#45]
现在程序无法从CDN或者orgin上面抓取图片了，停止在几天前的状态，想问下怎么解决，谢谢

**Comment by bitdust** [comment]
求详细

**Comment by leon0625** [comment]
我上周四刚用上，周五就不行了，好忧伤。直接wget下载图片，提升403 forbidden。不会这么巧就封了吧

**Comment by bitdust** [comment]
确实，服务器端现在返回403 forbidden
正在确认状况

**Comment by bitdust** [comment]
似乎恢复了

**Comment by ljxfstorm** [comment]
好像是源站出了问题，不过目前图像已经能正常获取了。
ImageID似乎还有问题，我当前时间2017/06/28 19:10 CST，然而log里看获取到的ImageID为2017/06/28/104000。
