### ISSUE TITLE
增加一点点小判断，在Widnows10下设置壁纸填充方式为“适应”？

### ISSUE THREAD

**Issue by Zhang-Siyang** [bitdust/EarthLiveSharp#47]
常常在物业发现壁纸怎么老是不换呢？打开设置才发现是 居中 模式，换为适应就好了

又熬夜熬得很困……不详细写了好吗？ 请看 [机房工具](https://github.com/Zhang-Siyang/F2Github/blob/master/JifangZhuanyong.Push.bat) 中我写到的：

```
%regadd%" /v TileWallpaper /d "0" /f
::0为居中，1为平铺
%regadd%" /v Wallpaper /d "%~d0\Mine\壁纸\wallhaven-312106.jpg" /f
%regadd%" /v WallpaperStyle /d "10" /f
::WallpaperStyle6为适应，2为拉伸，10为填充
start RunDll32.exe USER32.DLL,UpdatePerUserSys
```

具体的开发文档您还是找一找 MicroSoft 的官方文档吧，我这是从网络上找的，可能不是很准

**Comment by bitdust** [comment]
尝试了之后发现还是居中更合适一些~适应模式会有缩放模糊问题

**Comment by Zhang-Siyang** [comment]
@bitdust 昰这样的，要是我的屏幕是100x100分辨率的，而壁纸是300x300分辨率的，那居中会导致仅显示中间那 1/9 的壁纸，在本项目中，壁纸和屏幕纵高可能不能达到调和，所以增添居中选项是有必要性的

**Comment by Zhang-Siyang** [comment]
> 我设置了更高的分辨率，应该是 1100x1100，遗憾的是我现在转移到 Ubuntu + Hackintosh了
两块屏幕，1366x768 和 1920x1080；当768搭配1100的图片就会……不过我还是建议用系统的壁纸缩放，[也许]活少，优雅

**Comment by bitdust** [comment]
为了防止以后有人遇到同样问题，这里建议在出现“屏幕分辨率小于壁纸分辨率”时设置图片缩放比例到合适大小即可。顺便一提，这个功能在之前版本已经实现好了。但是我自己忘了~
