### ISSUE TITLE
可以通过修改配置文件使用origin源而不弹出提示么

### ISSUE THREAD

**Issue by myloft** [bitdust/EarthLiveSharp#52]

**Comment by bitdust** [comment]
不推荐长期使用orgin源

**Comment by myloft** [comment]
网络连通性足够好 为什么不能使用Origin呢 CDN需要定期清理有点麻烦

**Comment by bitdust** [comment]
CDN定时清理的问题在新版本已经解决。新版本中会自动清理过期图片。
使用CDN的主要目的是减轻对源服务器的压力，防止日本方面察觉到异常流量，关停服务或者更换接口。

**Comment by Doracoin** [comment]
@myloft 
防止官方更换、关闭接口，希望大家都节约使用流量

**Comment by myloft** [comment]
谢谢 配置完CDN后切回Origin 不会弹窗
