### ISSUE TITLE
建议增加“仅下载”壁纸的功能

### ISSUE THREAD

**Issue by windrunner337** [bitdust/EarthLiveSharp#55]
双屏机器，如果用EarthLiveSharp的话两个显示器强制显示同一个壁纸
想用DisplayFusion管理桌面壁纸，这样可以设置其中一个显示器显示地球壁纸
但是如果和EarthLiveSharp同时开启的话，这两个程序会交替的切换壁纸……
如果能增加仅下载功能就好了，这样多屏的用户就可以用DisplayFusion设置某个显示器调用EarthLiveSharp下载的壁纸了

**Comment by bitdust** [comment]
听起来不错，这个会有的，但是个人原因，下一次更新要拖到一年后了。你试试0.9版本的程序，当时没做自动设置壁纸功能，仅是下载壁纸。
或者你着急的话留个邮箱，我给你发一个定制版本的程序

**Comment by bitdust** [comment]
@windrunner337 您可以试下新发布的v3.8版本，可以在设置选项中禁用设置壁纸功能。
