### ISSUE TITLE
怎么控制图像百分比到50以下？

### ISSUE THREAD

**Issue by Wangzhiran** [bitdust/EarthLiveSharp#57]
我试了下高分辨率的，比如4000x4000和8000x8000，但是最低百分比只能调到51就不能往下了，然后地球壁纸就太大了超出屏幕范围了，无法适配屏幕。

**Comment by bitdust** [comment]
所以不建议使用超高分辨率。
讲道理，为了提高显示质量，需要尽可能避免图像二次缩放。4000x4000图像质量然后缩小50%的画质会比直接用2000x2000的更差。
使用适合的图像大小然后适当微调现实尺寸就可以了。

**Comment by Wangzhiran** [comment]
好的，了解啦




---原始邮件---
发件人: "bitdust"<notifications@github.com>
发送时间: 2019年8月22日(星期四) 晚上9:50
收件人: "bitdust/EarthLiveSharp"<EarthLiveSharp@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"Wangzhiran"<995886426@qq.com>;
主题: Re: [bitdust/EarthLiveSharp] 怎么控制图像百分比到50以下？ (#57)



所以不建议使用超高分辨率。
 讲道理，为了提高显示质量，需要尽可能避免图像二次缩放。4000x4000图像质量然后缩小50%的画质会比直接用2000x2000的更差。
 使用适合的图像大小然后适当微调现实尺寸就可以了。
