### ISSUE TITLE
设定为自动启动后，直接双击启动程序，不弹出窗口

### ISSUE THREAD

**Issue by SilverBut** [bitdust/EarthLiveSharp#6]
复现：配置中“Autostart”置为真，保存，关闭程序。再次启动程序，程序只会后台静默启动，不在前台弹出窗口。
另外已经启动程序的情况下，再次启动程序，没有任何提示（既没有提示已经有运行的进程，也没有弹出现有程序的设置窗口，也没有再次启动）

**Comment by bitdust** [comment]
是的，这个是为了开机自动启动设计的。我觉得作为一个壁纸软件不需要刷太多的存在感。
如果你想唤出窗口，直接点任务栏里的图标就可以了。
PS：如果有可能的话，图标我都不想要，但是这样的话需要加服务项，就太不“绿色了”。
