### ISSUE TITLE
无法将CDN设置为图像源

### ISSUE THREAD

**Issue by EdgeStar** [bitdust/EarthLiveSharp#62]
我已经按照教程注册并获得了云名称、api密钥以及api机密，然后将其填入设置，但是却无法保存，每次保存退出之后再进入设置就会又变成如图所示的默认orgin源
![image](https://user-images.githubusercontent.com/58938653/76318005-0441af80-6318-11ea-9a88-57e3a30d4d41.png)

检查配置文件发现add key="source_selection" value="0" ，手动修改为1也好像没什么用，求问有没有解决方法

**Comment by bitdust** [comment]
这是个神奇的错误。我刚测试确实现在发布的版本存在这个情况，但是在重新编译后，这个问题消失了。
您可以试下我现在的这个文件，替换一下您的可执行文件，试试这个程序是否可以正常工作。

[EarthLiveSharp.zip](https://github.com/bitdust/EarthLiveSharp/files/4314204/EarthLiveSharp.zip)

**Comment by EdgeStar** [comment]
> 这是个神奇的错误。我刚测试确实现在发布的版本存在这个情况，但是在重新编译后，这个问题消失了。
> 您可以试下我现在的这个文件，替换一下您的替换文件，试试这个程序是否可以正常工作。
> 
> [EarthLiveSharp.zip](https://github.com/bitdust/EarthLiveSharp/files/4314204/EarthLiveSharp.zip)

非常感谢，替换后可以正常使用了

**Comment by bitdust** [comment]
也多谢反馈！我也要马上更新下发布版本，避免其他人遇到同样问题。
