### ISSUE TITLE
软件在后台无法自动启动和自动更换壁纸

### ISSUE THREAD

**Issue by cilvky** [bitdust/EarthLiveSharp#63]
使用环境：win10 1909 版本
软件版本：3.8 版
之前使用3.7版本一直正常，在更新用3.8版本后就会有这种问题。开机软件自启动后能在任务管理器看到在后台进程，但是在通知区托盘图标没有显示，要自己重新启动软件才有托盘图标显示的后台图标。
桌面壁纸也不会自动更换，但是打开软件目录可以发现图片缓存一直都有更新，在桌面个性化设置也能在“选择图片”上看到更新的壁纸，只是不会自动切换。我这边不清楚是系统还是软件的问题，麻烦您帮忙看下怎么解决，谢谢！

**Comment by bitdust** [comment]
多谢反馈，我手边目前没有调试环境。请优先使用3.7版本~

**Comment by bitdust** [comment]
[EarthLiveSharp.zip](https://github.com/bitdust/EarthLiveSharp/files/4468827/EarthLiveSharp.zip)

您可以试下上面这个版本的程序，直接替换exe即可。看看这个有问题没？

**Comment by cilvky** [comment]
我这边直接替换exe测试一下，问题依旧存在，还是无法自启，但是软件的启动速度比之前的版本都要快很多。您之前说可以先换回3.7版本使用，我也试过但是没用，还是无法自启，不清楚是不是我系统的问题，麻烦您再看下是哪方面出问题了，谢谢！

**Comment by bitdust** [comment]
刚才我找了台windows10 x64 1909的电脑测试了下，不过没有复现问题。
1. 请试试在 settings 中重新勾选“Autostart”选项，因为添加的自启动可能会意外失效
2. 您的电脑是否在校园网环境？因为某些网络环境中，开机后没有网络连接，可能会导致意外的崩溃。
3. 给您发送的这个程序应该是代码重构后的版本。3.7版本确实写的不好，原3.8版本的代码有些bug。所以您还是使用这个程序即可，可以在重新勾选“autostart”后观察重启后有没有进程出现。

**Comment by cilvky** [comment]
谢谢，我这边是用的是宽带，应该不会受到网络的影响。我用(1)的方式试了下，但还是无法自启动，应该是我自己系统的问题吧。您发给我的新版本很流畅，不会有卡死的现象了，我这边手动开启软件就行了，谢谢您！

**Comment by bitdust** [comment]
同样多谢您的反馈
