### ISSUE TITLE
请问，能否增加Socks代理，以及其他卫星图源选项？

### ISSUE THREAD

**Issue by zsbstephen** [bitdust/EarthLiveSharp#64]
先感谢作者做出这么好的桌面小工具。

RT，如果支持Socks代理的话，就可以调用v2ray或者shadowsocks代理来访问hiwamari的图源，比使用cloudinary更快，毕竟电信163的国际出口QOS、延迟和丢包率真不是盖的……

另外，hiwamari8虽然图像质量高、清晰，但因为毕竟是日本的卫星轨道定点中央是日本，导致中国大陆西边看不到。如果支持选择风云4号星的云图就更好了，可以上帝视觉看中国。

**Comment by AspirinEny** [comment]
附议。

**Comment by bitdust** [comment]
谢谢提议，这项工作应该会在下个大版本中完成~
