### ISSUE TITLE
无法连接远程服务器怎么办？

### ISSUE THREAD

**Issue by Zjh997** [bitdust/EarthLiveSharp#65]
注册了CDN，设置好执行的时候，桌面一片漆黑，现在是白天，trace.log文件显示“无法连接远程服务器”

**Comment by bitdust** [comment]
疑似官方服务器挂了。这个需要多等等了

**Comment by Zjh997** [comment]
以前挂过吗？大概要等多久啊

**Comment by bitdust** [comment]
挂过，一两天吧。
肯定能恢复，日本人很敬业的。但毕竟不是商业服务，所以不会马上复原。

**Comment by Zjh997** [comment]
ok 等等看吧

**Comment by Zjh997** [comment]
现在连得上了
