### ISSUE TITLE
获取lastest.json地址更新了，建议改成可配置的方式

### ISSUE THREAD

**Issue by YoungHnhb** [bitdust/EarthLiveSharp#67]
https://github.com/bitdust/EarthLiveSharp/blob/99c5a6c2b0da41d73fddf40ba648516e61d90402/EarthLiveSharp/Program.cs#L99

最新的地址已经是https://himawari8-dl.nict.go.jp/himawari8/img/D531107/latest.json了，是不是可以改成可动态修改的请求地址会好点

**Comment by GEEK-WALKER** [comment]
原来是JMA把地址给改了，我说怎么这几天突然就不能用了

**Comment by bitdust** [comment]
多谢反馈，请尝试新版本

https://github.com/bitdust/EarthLiveSharp/releases
