### ISSUE TITLE
软件点击开始后桌面是黑色的不更新壁纸

### ISSUE THREAD

**Issue by YuShengSenior** [bitdust/EarthLiveSharp#69]
下载配置CDN后壁纸还是出不来一直都是黑色的
![image](https://user-images.githubusercontent.com/53929086/92346965-1357bd80-f101-11ea-86ba-78bcdb732b1b.png)

**Comment by FredLin0513** [comment]
软件没问题，[是获取图片的地址变了](https://github.com/bitdust/EarthLiveSharp/issues/67)。等作者更新或者自己改地址

**Comment by bitdust** [comment]
已修复 请尝试新版本。
https://github.com/bitdust/EarthLiveSharp/releases
