### ISSUE TITLE
配置文件中图片文件夹无效时，程序无法启动

### ISSUE THREAD

**Issue by SilverBut** [bitdust/EarthLiveSharp#7]
复现：程序启动一次后关闭，再移动到另外的一个文件夹，再次启动。
现象：程序假死后退出
OS版本：Windows 10 10586
目前已知的缓解办法是，手动清空Config文件中该配置项的值。

**Comment by bitdust** [comment]
谢谢反馈~我会修正这个bug的。

**Comment by bitdust** [comment]
@SilverBut 
征求下意见，你觉得“选择图片存储位置”这个需求有必要吗？
如果没必要的话，我打算写死图片存储在images文件夹里，这样就可以避免类似的文件读写带来的bug了。

**Comment by SilverBut** [comment]
@bitdust 
感觉没必要，不过也不要存在Images文件夹里吧
既然你用C#写的程序，实际配置文件和资源啥的都可以存到%APPDATA%下面啊，也不需要UAC

**Comment by bitdust** [comment]
明白了，谢谢

**Comment by bitdust** [comment]
fixed in version 1.1
