### ISSUE TITLE
疑似图片下载地址变更

### ISSUE THREAD

**Issue by LGinC** [bitdust/EarthLiveSharp#70]
https://himawari8-dl.nict.go.jp/himawari8/img/D531107/latest.json 返回
`{"date":"2020-09-08 04:17:30","file":"PI_H08_20200908_0410_TRC_JP04_R10_PLLJP.png"}`

拼接后图片地址
[http://himawari8-dl.nict.go.jp/himawari8/img/D531106/1d/550/2020/09/08/041730_0_0.png](http://himawari8-dl.nict.go.jp/himawari8/img/D531106/1d/550/2020/09/08/041730_0_0.png)
返回404 Not Found
疑似图片地址拼接方式也变更了

**Comment by YY590** [comment]
什么时候恢复

**Comment by bitdust** [comment]
已修复 请尝试新版本。
https://github.com/bitdust/EarthLiveSharp/releases
