### ISSUE TITLE
V3.10获取图片失败

### ISSUE THREAD

**Issue by YoungHnhb** [bitdust/EarthLiveSharp#72]
![image](https://user-images.githubusercontent.com/41976350/93281849-8fd45580-f7ff-11ea-852a-a8d707076b55.png)
获取图片失败，这个要怎么解？
是需要科学上网吗？

**Comment by YoungHnhb** [comment]
如题

**Comment by bitdust** [comment]
似乎是网络问题。

我这里也检测到时不时的连不上日本服务器。

**Comment by YoungHnhb** [comment]
昨天运行起来就没再管他了，到下午突然就正常了，感觉跟预热完成似的，到目前都是正常的，哈哈哈哈     : )

**Comment by knight-666** [comment]
[himawari8 get latest ImageID] 2020/09/21/070000
远程服务器返回错误: (400) 错误的请求。 2020/09/21/070000
[url]https://res.cloudinary.com/dtma0mhwv/image/fetch/https://himawari8-dl.nict.go.jp/himawari8/img/D531106/8d/550/2020/09/21/070000_0_0.png [image_path]C:\EarthLiveSharp3.10\images\0_0.png


一直报这个错
