### ISSUE TITLE
作者可以考虑一下离线模式吗

### ISSUE THREAD

**Issue by RiverFlowsInUUU** [bitdust/EarthLiveSharp#73]
作者可以考虑一下离线模式吗
把一天的图全部下载到PC中，放在本地用于自动更换壁纸。
ps 鉴于我不知道的原因，壁纸经常更换失败，通过挂代理或者CDN方法，现在3.1版本，地球一直不动。一次性下载所有壁纸，离线自动更换算是一种曲线救国的方法，弥补体验吧。
个人建议，希望作者可以考虑一下，谢谢。

**Comment by bitdust** [comment]
你可以使用软件自带的下载功能，把一段时间内的图片保存在本地。

然后在windows壁纸程序中设置循环播放即可

**Comment by RiverFlowsInUUU** [comment]
目前我是用CDN和源数据都试过了，地球不动。没有图片存在本地。

bitdust <notifications@github.com>于 2020年9月16日 下午7:55写道：

你可以使用软件自带的下载功能，把一段时间内的图片保存在本地。

然后在windows壁纸程序中设置循环播放即可

**Comment by bitdust** [comment]
因为需要从官方服务器那里获得最新的图片信息，最近这个接口确实时常出问题。

这个确实没法通过设置CDN解决。

未来我可能会考虑发掘一下更多的图片源（包括风云卫星的），来提供一些可替代性。

**Comment by RiverFlowsInUUU** [comment]
好的谢谢，不过我比较钟爱🌻向日葵八号。😊

bitdust <notifications@github.com>于 2020年9月16日 下午9:05写道：
