### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ABPW10** [bitdust/EarthLiveSharp#76]

**Comment by qzwl** [comment]
> https://github.com/bitdust/EarthLiveSharp/blob/c5406d78be9373446e476f04e4dded2c423f77bc/EarthLiveSharp/Program.cs#L137
> 
> https://github.com/ABPW10/EarthLiveSharp/blob/890998f666da270b0e05adac27ac7a3662e1f8e4/EarthLiveSharp/Program.cs#L137

你有没有生成EXE
