### ISSUE TITLE
Cannot automatically refresh after sleeping

### ISSUE THREAD

**Issue by SykieChen** [bitdust/EarthLiveSharp#9]
After recovering from a sleep, the program can normally download new pics, but not refreshing.

**Comment by bitdust** [comment]
Wait for some minutes?
Perhaps your network cant resume as soon as windows is waked up.
But the timer will procees its task and try to update at next tick.

要不试试多等一会儿？
很大可能是因为你的系统被唤醒时，网络没有马上恢复，造成了图片下载失败。但是此时程序的计时器仍在工作，所以在下一个周期时，程序仍然会尝试去下载图片。
如果还不行的话，贴下那个trace.log出来看看？log文件就在你的可执行文件目录下面

**Comment by SykieChen** [comment]
I accidentally restarted the program and the log was automatically cleared :(
But I'm sure the pic was downloaded successfully cause I can see it in the folder and change it manually in the system as wallpaper.
Somehow it didn't automatically change the wallpaper. I'll watch this issue and send the log when it happens again.

刚才重启程序结果日志自动清了=。=
但我确定图已经下载成功，在图片目录中可以看到，在系统设置手动更改壁纸成功。
只是不知什么原因没有自动地更新壁纸。如果再次重现我会上传日志~
